backend:
  name: github
  repo: cronicasdelermitano/cronicas-del-ermitano

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "escritos"
    label: "Escritos"
    folder: "escritos"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Texto", name: "body", widget: "markdown" }
